"""Read-only evidence ledger for the training-strategy audit."""
import json,sys,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'src'))
from gameboy_agent.navigation import NavigationNet
READ=lambda p:json.loads(Path(p).read_text())
def main():
 names=[f'navigation-routes-v{i}' for i in range(1,10)]+['navigation-sword-v1','navigation-sword-v2','navigation-cliff-specialists-v1','navigation-cliff-specialists-v2'];rows=[];sources={}
 for name in names:
  path=ROOT/f'reports/{name}.json';r=READ(path);sources[str(path.relative_to(ROOT))]=hashlib.sha256(path.read_bytes()).hexdigest();routes=r.get('routes',r.get('candidate',{}).get('routes',[]));panels=r['local_panels'];score=[panels[n].get('successes',panels[n].get('corrected_successes')) for n in ['original','additional','fresh']];ep=ROOT/f'runs/{name}/evaluation-plan.json';plan=READ(ROOT/f'runs/{name}/plan.json')
  rows.append(dict(name=name,local_successes=score,candidate_local_cases=sum(p['cases'] for p in panels.values()),explicit_local_rollouts=READ(ep)['local_rollouts'] if ep.exists() else None,route_cases=len(routes),route_successes=sum(x['status']=='success' for x in routes),route_waypoints=sum(x.get('waypoints',x.get('progress',{}).get('cursor',0)) for x in routes),route_damage=sum(x.get('damage',x.get('navigation_damage',0)) for x in routes),chain_cases=len(r['continuous']) if isinstance(r['continuous'],list) else None,selected_or_eligible=r.get('eligible',r.get('promoted',False)),epochs=plan.get('epochs'),reserved_evaluation_used=r['reserved_evaluation_used'],completion_evaluated=r['completion_evaluated']))
 batch=READ(ROOT/'runs/data-workset-16m-v1/status.json');stress=READ(ROOT/'reports/navigation-cliff-stress-v1.json');params=sum(p.numel() for p in NavigationNet(250).parameters());ppo=READ(ROOT/'runs/overnight-fixed-20260910-090710/status.json')
 ledger=dict(scope='13 bounded candidate experiments: routes v1-v9, sword v1-v2, cliff specialists v1-v2. Earlier navigation/recovery/PPO/teacher searches are excluded from candidate-rollout totals.',candidates=rows,candidate_count=len(rows),candidate_local_cases=sum(x['candidate_local_cases'] for x in rows),documented_local_rollout_lower_bound=sum(x['explicit_local_rollouts'] or x['candidate_local_cases'] for x in rows),candidate_route_rollouts=sum(x['route_cases'] for x in rows),mlp_parameters=params,selected_three_network_parameters=3*params,data_collection=dict(actions=batch['rows'],episodes=batch['episodes'],active_seconds=batch['active_seconds'],active_minutes=batch['active_seconds']/60,committed_bytes=batch['bytes'],committed_gib=batch['bytes']/2**30,reported_process_cpu_seconds=batch['resources']['process_cpu_seconds'],reported_process_cpu_hours=batch['resources']['process_cpu_seconds']/3600,notes='CPU counter is the supervisor status field; not a complete project-wide CPU ledger. Collection actions are not optimizer-training steps or expert demonstrations.'),earlier_ppo=dict(completed=sum(x['status']=='completed' for x in ppo['runs']),failed=sum(x['status']=='failed' for x in ppo['runs']),batch_wall_seconds=ppo['finished_at']-ppo['started_at'],completion_evaluated=ppo['completion_evaluated']),stress_summary=stress['perturbed'],sources=sources,resource_accounting_limits=['No unified measured train/evaluate/collect wall-time and compute ledger across the 13 candidate experiments.','No reliable recorded human/assistant effort, token spend, monetary cost or energy allocation for the research loop.','Do not estimate cumulative compute from epoch counts, file modification times or collection throughput.'],new_training_performed=False)
 (ROOT/'reports/training-process-audit.json').write_text(json.dumps(ledger,indent=2));print(json.dumps({k:v for k,v in ledger.items() if k not in ('candidates','sources','resource_accounting_limits')},indent=2));print('CANDIDATES',[(x['name'],x['route_successes'],x['local_successes']) for x in rows])
if __name__=='__main__':main()
